# Generated by Django 2.2.5 on 2019-11-10 14:51

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'drill',
                'verbose_name_plural': 'drills',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateField(verbose_name='date')),
                ('weight', models.IntegerField(verbose_name='weight')),
                ('round', models.IntegerField(verbose_name='round')),
                ('repetition', models.IntegerField(verbose_name='repetition')),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exerlogger.Drill', verbose_name='drill')),
            ],
            options={
                'verbose_name': 'workout',
                'verbose_name_plural': 'workouts',
            },
        ),
    ]
