# Generated by Django 2.2.5 on 2019-11-10 16:07

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exerlogger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='drill',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='repetition',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='round',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='weight',
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateField(verbose_name='date')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='weight')),
                ('round', models.IntegerField(verbose_name='round')),
                ('repetition', models.IntegerField(verbose_name='repetition')),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exerlogger.Drill', verbose_name='drill')),
            ],
            options={
                'verbose_name': 'exercise',
                'verbose_name_plural': 'exercises',
            },
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(to='exerlogger.Exercise', verbose_name='exercises'),
        ),
    ]
