# Generated by Django 3.0.3 on 2020-08-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exerlogger', '0002_auto_20200817_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='equipment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='exerlogger.Equipment', verbose_name='equipment'),
        ),
    ]
