# Generated by Django 2.2.5 on 2020-01-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerlogger', '0002_gym_lesson_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='weekdays',
            field=models.CharField(max_length=255, verbose_name='weekdays'),
        ),
    ]
