# Generated by Django 2.2.5 on 2019-11-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exerlogger', '0003_workout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='date',
        ),
    ]
