# Generated by Django 3.0.3 on 2020-08-18 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exerlogger', '0003_auto_20200817_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exerlogger.Equipment', verbose_name='equipment'),
        ),
    ]
