# Generated by Django 3.0.3 on 2020-08-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerlogger', '0004_auto_20200818_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='form',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
