# Generated by Django 2.2.5 on 2020-01-04 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerlogger', '0005_customuser_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='training',
        ),
        migrations.AddField(
            model_name='training',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
