# Generated by Django 2.2.5 on 2020-01-07 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exerlogger', '0006_auto_20200104_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exerlogger.Lesson', verbose_name='lesson'),
        ),
    ]
