# Generated by Django 2.2.5 on 2019-11-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerlogger', '0006_auto_20191112_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='repetition',
            field=models.IntegerField(default=1, verbose_name='repetition'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='round',
            field=models.IntegerField(default=1, verbose_name='round'),
        ),
    ]
