# Generated by Django 2.2.5 on 2020-01-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerlogger', '0008_auto_20200107_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='drill',
            field=models.ForeignKey(on_delete=models.SET('Drill no longer exists'), to='exerlogger.Drill', verbose_name='drill'),
        ),
        migrations.AlterField(
            model_name='training',
            name='lesson',
            field=models.ForeignKey(on_delete=models.SET('Lesson no longer exists'), to='exerlogger.Lesson', verbose_name='lesson'),
        ),
    ]
