# Generated by Django 2.2.5 on 2020-03-20 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exerlogger', '0009_auto_20200107_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='users',
            new_name='participants',
        ),
    ]
