# Generated by Django 2.2.5 on 2020-03-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerlogger', '0012_auto_20200320_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='var_num',
            field=models.IntegerField(null=True, unique=True, verbose_name='var_num'),
        ),
    ]
