# Generated by Django 2.2.5 on 2020-03-20 20:10

import datetime
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exerlogger', '0013_customuser_var_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('money', models.DecimalField(decimal_places=2, max_digits=6)),
                ('var_num', models.IntegerField(null=True, unique=True, verbose_name='var_num')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
    ]
