# Generated by Django 2.2.5 on 2020-03-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerlogger', '0014_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='var_num',
            field=models.IntegerField(null=True, verbose_name='var_num'),
        ),
    ]
