# Generated by Django 2.2.5 on 2020-03-22 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerlogger', '0016_auto_20200322_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +420123456789.', regex='^\\+\\d{12}$')]),
        ),
    ]
