# Generated by Django 2.2.5 on 2020-03-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerlogger', '0017_auto_20200322_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='kb5_level',
            field=models.IntegerField(max_length=1, null=True, verbose_name='kb5_level'),
        ),
    ]
