# Generated by Django 2.2.5 on 2020-03-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerlogger', '0018_drill_kb5_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='kb5_level',
            field=models.IntegerField(blank=True, max_length=1, null=True, verbose_name='kb5_level'),
        ),
    ]
