# Generated by Django 2.2.5 on 2020-04-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerlogger', '0020_customuser_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='kb5_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='kb5_level'),
        ),
    ]
