# Generated by Django 2.2.5 on 2020-04-11 10:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exerlogger', '0021_auto_20200411_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='membership',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='membership'),
        ),
    ]
