# Generated by Django 3.0.7 on 2020-08-06 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exerlogger', '0022_auto_20200411_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'equipment',
                'verbose_name_plural': 'equipments',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name': 'form',
                'verbose_name_plural': 'forms',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('unit', models.CharField(max_length=8)),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='repetition',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='round',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='weight',
        ),
        migrations.AddField(
            model_name='drill',
            name='bilateral',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
                ('consists', models.ManyToManyField(to='exerlogger.Drill')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(default=1, verbose_name='sets')),
                ('reps', models.IntegerField(default=1, verbose_name='reps')),
                ('equipment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='exerlogger.Equipment', verbose_name='equipment')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exerlogger.Exercise', verbose_name='exercise')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exerlogger.Property', verbose_name='property'),
        ),
        migrations.AddField(
            model_name='drill',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='exerlogger.Form'),
        ),
    ]
