# Generated by Django 3.0.7 on 2020-08-07 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exerlogger', '0023_auto_20200806_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exerlogger.Workout', verbose_name='workout'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='exerlogger.Exercise', verbose_name='exercise'),
        ),
    ]
