# Generated by Django 3.0.7 on 2020-08-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exerlogger', '0024_auto_20200807_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='consists',
            new_name='drills',
        ),
    ]
