# Generated by Django 3.0.7 on 2020-08-12 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exerlogger', '0026_auto_20200812_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='exerlogger.Property', verbose_name='property'),
        ),
    ]
