# Generated by Django 3.0.7 on 2020-08-12 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exerlogger', '0027_auto_20200812_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='exerlogger.Equipment', verbose_name='equipment'),
        ),
    ]
