# Generated by Django 3.0.7 on 2020-08-12 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exerlogger', '0028_auto_20200812_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='exerlogger.Equipment', verbose_name='property'),
        ),
    ]
